### ISSUE TITLE
About the downstream filtering of GATK-SV pipeline

### ISSUE THREAD

**Issue by elitefugua** [ruthchia/Structural_variant_analysis-LBD-FTD#1]
Hello, @ruthchia. I have read the paper “Genome-wide structural variant analysis identifies risk loci for non-Alzheimer’s dementias”, and I am working on a similar research about the structure variants. In the method section you mentioned that the downstream filtering of the GATK-SV pipeline had been conducted. However, it seems that the module 07 of GATK-SV, which can be used to apply downstream filtering steps (minGQ filtering, FilterOutlierSamples, BatchEffect, and FilterCleanupQualRecalibration) to the cleaned VCF, is still in development. Thus, I wonder how these downstream filtering were performed in your study. 
Thank you very much for your attention and consideration.
Looking forward to your reply.

**Comment by kkaivola** [comment]
Hi, please see the answer posted at https://github.com/kkaivola/LBD_FTD_Structural_variants/issues/1 . I will close this thread as a duplicate.
